import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createMemoryHistory, RouterProvider } from '@tanstack/react-router'
import { render } from '@testing-library/react'
import { vi } from 'vitest'
import type { HomeView, ShellView } from '../lib/api'
import { createAppRouter } from '../router'
import homeJson from './fixtures/home.json'
import shellJson from './fixtures/shell.json'

// Generated by `kestrel demo --view ...`; tests/test_generated_files.py keeps them in step with the Python code.
export const homeFixture = homeJson as unknown as HomeView
export const shellFixture = shellJson as unknown as ShellView

/** The whole app at `path`, with the API answered from fixtures. Any real network call fails the test. */
export function renderApp(path = '/', data: { home?: HomeView; shell?: ShellView } = {}) {
  vi.stubGlobal('fetch', vi.fn(() => Promise.reject(new Error('network is off in tests'))))
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: Infinity } } })
  client.setQueryData(['home'], data.home ?? homeFixture)
  client.setQueryData(['shell'], data.shell ?? shellFixture)
  const router = createAppRouter(createMemoryHistory({ initialEntries: [path] }))
  const view = render(
    <QueryClientProvider client={client}>
      <RouterProvider router={router} />
    </QueryClientProvider>,
  )
  return { ...view, router, client }
}
